Delivercancel orders api
developers-bootcamp/order-manager-red pull request #33
Opened 2023-07-24 09:05 UTC by Elisheva1234

2023-07-29 23:22 UTC, moriyahazan commented on src/main/java/com/sapred/ordermanagerred/service/OrdersStatusService.java
> +                project()
You should select the order related to the company id from token

2023-07-29 23:23 UTC, moriyahazan requested changes

2023-07-29 23:23 UTC, moriyahazan commented on src/main/java/com/sapred/ordermanagerred/service/OrdersStatusService.java
> +        AggregationResults<Document> results = mongoTemplate.aggregate(aggregation, "Orders", Document.class);
You should select the order related to the company id from token

2023-07-29 23:23 UTC, moriyahazan commented on src/main/java/com/sapred/ordermanagerred/service/OrdersStatusService.java
> +        AggregationResults<Document> results = mongoTemplate.aggregate(aggregation, "Orders", Document.class);
In additon the status should be from enum and not 0/1

2023-08-13 18:52 UTC, moriyahazan commented
@Elisheva1234 Why this PR still open, did you see my comments?

2023-08-13 20:28 UTC, Elisheva1234 commented
זה לא הPR שלי פתחתי אותו בשביל פניני פרידמן שלא יכלה לעשות את זה
לעצמה.......
עדכנתי אותה שכתבת לה הערות ואין לי מושג מה עם זה
המייל שלה: "פ.פרידמן" ***@***.***>

‫בתאריך יום א׳, 13 באוג׳ 2023 ב-21:52 מאת ‪Moriya‬‏ <‪
***@***.***‬‏>:‬

> @Elisheva1234 <https://github.com/Elisheva1234> Why this PR still open,
> did you see my comments?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/developers-bootcamp/order-manager-red/pull/33#issuecomment-1676435870>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BAU34K5KWUOHY3GXSF3F2O3XVEPAFANCNFSM6AAAAAA2VIRODQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-21 12:18 UTC, Elisheva1234 commented
הי מוריה,
כאן פניני פרידמן.
אני לא הצלחתי לקבל ממך עדיין הרשאה לדחוף(שלחתי כמה מיילים וכנראה לא ראית...)
אז עשיתי את הכל דרך אלישבע, למעשה, דבר ראשון אני אשמח שתוסיפי לי את ההרשאה שאני אוכל להתקדם.:p0583289998@gmail.com
לגבי הpull request הנוכחי,
את ההערה הראשונה עשיתי(token), את השנייה(0/1) אף אחת משלושת הקבוצות לא הצליחה לעשות, נשמח לעזרה או שעדיף לוותר על זה?
תודה רבה!

2023-08-21 20:10 UTC, moriyahazan commented
שלחתי לך זימון

2023-08-23 13:21 UTC, PninaFriedman commented
הי מוריה
סיימתי את התיקונים אני אשמח שתאשרי לי.
תודה!

2023-08-23 22:16 UTC, moriyahazan approved these changes

2023-08-24 06:25 UTC, merged